server:
  port: 5001
spring:
  application:
    name: jia

  datasource:
    #jdbc:mysql://139.199.17.156:3306/lostandfound
    url: jdbc:mysql://localhost:3306/lar
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


