server:
  port: 5001
spring:
  application:
    name: jia

  datasource:
    url: **
    #url: jdbc:mysql://localhost:3306/lar
    username: **
    password: **
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
        properties:
          hibernate:
            hbm2ddl:
              auto: update
